import = ["~/.config/alacritty/themes/everforest_dark.toml"]

[env]
term = "xterm-256color"

[font]
size = 12

[font.normal]
# family = "JetBrainsMono Nerd Font"
# family = "Fira Mono"
# family = "UbuntuMono Nerd Font Mono"
family = "DejaVuSansM Nerd Font Mono"
# family = "Terminess Nerd Font Mono"
# style = "bold"

[window]
decorations = "none"
#startup_mode = "Maximized"
# opacity = 0.85

[scrolling]
history = 20000
multiplier = 5

#[cursor]
#style = { shape = "Beam", blinking = "Always" }
#blink_interval = 750

[window.padding]
x = 5
y = 5
